const MutationTypes = {
  SET_HORSES: 'SET_HORSES',
  SET_SCHEDULE: 'SET_SCHEDULE',
  SET_RUN_RESULT_WITH_FINISH_TIMES: 'SET_RUN_RESULT_WITH_FINISH_TIMES',
  SET_GENERATED: 'SET_GENERATED',
  SET_FINISHED: 'SET_FINISHED',
  SET_RUNNING: 'SET_RUNNING',
  SET_PAUSED: 'SET_PAUSED',
} as const

export { MutationTypes }
